### ISSUE TITLE
Progress reporting for QuickCheck seems to report progress over 100%

### ISSUE THREAD

**Issue by michaelpj** [UnkindPartition/tasty#402]
I'm not really sure what's going on here, but I've seen progress reports from QuickCheck go over 100%. These are for tests where I've set `MaxSuccesses` to a higher number, so initially I thought we simply weren't dividing by the right thing. But the code [seems to be doing the right thing](https://github.com/UnkindPartition/tasty/blob/master/quickcheck/Test/Tasty/QuickCheck.hs#L251) so I'm not sure what's happening.

cc @coot

**Comment by michaelpj** [comment]
I don't _think_ this is anything to do with `QuickCheck` - that just reports the number of tests, which seems fine. I think it must be something about how we're converting that to a percentage...

**Comment by Bodigrim** [comment]
Maybe `tasty` way to parse QuickCheck messages is not entirely correct. Any chance that the tests in question have high discard rate?

**Comment by BebeSparkelSparkel** [comment]
Example of this problem

```
All
  Properties
    lowlevel
      input-output
        t_write_read:         384% 
```

when using `withMaxSuccess 1000 ...`

**Comment by BebeSparkelSparkel** [comment]
Error in this line https://github.com/UnkindPartition/tasty/blob/dcbf32078133aa2b569774c417cc49a49f5c573b/quickcheck/Test/Tasty/QuickCheck.hs#L267

**Comment by Bodigrim** [comment]
@BebeSparkelSparkel any idea what's exactly wrong with `parseProgress`?

**Comment by BebeSparkelSparkel** [comment]
@Bodigrim Nothing wrong with the parser. QuickCheck prints the number of tests run and not the % done. Also, the number of tests to run cannot be gotten with out running at least one test because withMaxSuccess does not modify the state nor args but rather the returned intermediate result that has the field [`maybeNumTests`](https://github.com/nick8325/quickcheck/blob/62c3353b0bb60a6958a74e57aa95aac79ecfed1c/src/Test/QuickCheck/Property.hs#L290).

I was thinking that an IORef could be added that holds the number of tests to run and then `mapResult` could be used with `unsafePerformIO` to update the number after one tests has been run.

I also added this issue since QuickCheck seems to not be a primary test framework but rather an add in tool. https://github.com/nick8325/quickcheck/issues/399

**Comment by Bodigrim** [comment]
@BebeSparkelSparkel I'm afraid it's hard for me to grasp. Can you possibly come up with a minimal standalone reproducer?

**Comment by Bodigrim** [comment]
OK, so the problem is that there are two ways to set number of tests to execute:

One is to use [`QuickCheckTests`](https://hackage.haskell.org/package/tasty-quickcheck-0.10.3/docs/Test-Tasty-QuickCheck.html#t:QuickCheckTests) on `TestTree` level, e. g., `localOption (QuickCheckTests 1000)`. This is a native `tasty-quickcheck` mechanism, which progress reporting knows about and handles well. 

But there is another way to set number of tests: apply [`withMaxSuccess`](https://hackage.haskell.org/package/QuickCheck-2.15/docs/Test-QuickCheck.html#v:withMaxSuccess) on `Property` level. This way it remains hidden from `tasty`, which continues to think that there are only 100 tests, thus misreporting progress.

@BebeSparkelSparkel is my understanding correct?

**Comment by BebeSparkelSparkel** [comment]
Yes. I really don't like how withMaxSuccess accomplishes this.

**Comment by MaximilianAlgehed** [comment]
You can always add a `callback` that uses an `IORef` to track the changes to `Result` that are made by `withMaxSuccess` and friends.

**Comment by Bodigrim** [comment]
@michaelpj could you please check whether HEAD fixes the issues you observed?

**Comment by michaelpj** [comment]
Yep, that fixes it! Thanks @BebeSparkelSparkel
